### ISSUE TITLE
New argument "make_cache_key" missing in the docs

### ISSUE THREAD

**Issue by reinoldus** [pallets-eco/flask-caching#222]
Since version 1.9 this argument is supported but not mentioned anywhere in the docs (except change log).

I can add it if I find the time. Though I am unsure where it is available, just using view caching for now:

I'd add something like that:

```
def make_key():
    user_data = request.get_json()

    return ",".join([f"{key}={value}" for key, value in user_data.items()])


@app.route("/hello", methods=["POST"])
@cache.cached(timeout=60 * 60, make_cache_key=make_key)
def some_func():
    ....

```

+ some text around it

**Comment by sh4nks** [comment]
While it's documented in the API Docs, an additional example can never hurt. Feel free to open a PR documenting this feature.

**Comment by ninadpchaudhari** [comment]
> While it's documented in the API Docs, an additional example can never hurt. Feel free to open a PR documenting this feature.

Thanks
Done. Please check PR #519
