### ISSUE TITLE
Maintainership

### ISSUE THREAD

**Issue by sh4nks** [pallets-eco/flask-caching#268]
Hey guys,

I am stepping down as maintainer due to time constraints and interests. I will be transferring the ownership to @pallets-eco, a place for community maintained Flask extensions.

Cheers

**Comment by snarfed** [comment]
Thank you for maintaining this plugin for the last seven years! It's huge, we're all very grateful. Best of luck!

**Comment by davidism** [comment]
Hi @sh4nks, just added you to pallets-eco so you should be able to finish the transfer.

**Comment by sh4nks** [comment]
@davidism, thanks! I just transfered the repo :-)
