### ISSUE TITLE
Unable to delete expired values; Access is denied; Windows 10

### ISSUE THREAD

**Issue by jmatteson-rtr** [pallets-eco/flask-caching#309]
Attempting to use FileSystemCache to save dataframes using get and set within a class function. When getting an expired value this error appears: delete key...  [WinError 32] The process cannot access the file because it is being used by another process: 

My config looks like this 
```python
config = {
        "DEBUG": True,          # some Flask specific configs
        "CACHE_TYPE": "FileSystemCache",  # Flask-Caching related configs
        "CACHE_DEFAULT_TIMEOUT": 5,
        "CACHE_DIR": ...relative path to dir ,
        "CACHE_THRESHOLD":0,
        "CACHE_OPTIONS":{"mode":777}
}
```
and the caching class looks like this 
```python

class CachedORMClass():
  ormTable=None
  cacheKey=None
  engine=None
  def __init__(self,ormTable,engine):
    self.ormTable=ormTable
    self.cacheKey=str(ormTable._sa_class_manager.mapper.mapped_table.schema)+"."+ str(ormTable._sa_class_manager.mapper.mapped_table.name)
    self.engine=engine

  def getData(self,extraClauses=None,as_DataFrame=None):
    if(self.cacheKey):
      cacheData = appCache.get(self.cacheKey)
      if(type(cacheData)==pd.DataFrame):
        print('getting cache data')
        return cacheData
      else:
        if(extraClauses!=None):
          sqlStatement = select(self.ormTable).where(extraClauses)          
          data = pd.read_sql(sqlStatement,con=self.engine)
          appCache.add(self.cacheKey,data,timeout=1)
          return data
        else:
          sqlStatement = select(self.ormTable)         
          data = pd.read_sql(sqlStatement,con=self.engine)
          appCache.add(self.cacheKey,data,timeout=1)
          return data
```

Environment:

- Python version: 3.9.7
- Flask-Caching version: 1.10.0

**Comment by jmatteson-rtr** [comment]
I've solved this and most of the issue appears to be that the os library is implemented differently on Windows OS thus functions like os.remove and os.chmod do not work as expected. Whenever the cache file is created, the chmod uses linux style octals that do not map to windows permissions, specifically the "read-only" property. I changed the FileSystemCache set function that creates the cache to: 
```python
os.chmod(filename, stat.S_IWRITE)
```
With this change, the app was able to delete existing cache files

**Comment by northernSage** [comment]
Handled in https://github.com/pallets-eco/cachelib/pull/158
