### ISSUE TITLE
FileSystemCache deletes every 3 caches when threshold is reached

### ISSUE THREAD

**Issue by xRagnorokx** [pallets-eco/flask-caching#312]
While stress testing an app using Flask-Cachings FileSystemCache I noticed that when the max number of allowed caches is reached (as set buy the Threshold Parameter) it seems to delete a huge number of caches. While deleting expired caches is expected behavior it seems to delete expired caches + a random sample of active caches totaling about 1/3rd of the threshold.

This seems to be confirmed by the code taken from https://github.com/pallets-eco/flask-caching/blob/5eef6738430a6887fce03552cb2438501e3dc741/flask_caching/backends/filesystemcache.py below, which (unless I'm reading this wrong) deletes expired caches when the threshold is reached but ALSO deletes every 3 caches in a unsorted list.

    def _prune(self):
        if self._threshold == 0 or not self._file_count > self._threshold:
            return

        entries = self._list_dir()
        now = time()
        for idx, fname in enumerate(entries):
            try:
                remove = False
                with open(fname, "rb") as f:
                    expires = pickle.load(f)
                remove = (expires != 0 and expires <= now) or idx % 3 == 0

                if remove:
                    os.remove(fname)
            except (IOError, OSError):
                pass
        self._update_count(value=len(self._list_dir()))

I would expect the caching system to (for each cache made over the limit) delete any expired caches and if still over the limit delete 1 more cache (the cache nearest to expiring). This would be equivalent I think to REDIS's 'volatile-ttl' setting. Alternatively 'volatile-lru', 'allkeys-lru' or at the very least 'volatile-random' approaches would also make sense, but not 'delete every third file'!

**Comment by northernSage** [comment]
Hey @xRagnorokx, thanks for the detailed explanation and for thanking the time to let us know about this. This has been changed in https://github.com/pallets/cachelib/pull/26 and flask-caching will inherit the new pruning behavior once integrated with cachelib (see #308).

**Comment by xRagnorokx** [comment]
Excellent, thanks for fixing this! We managed to avoid the issue by using redis for caching when staging or in production (which we needed regardless) but this will make local running/testing for dev require far less clearing of caches / disk space!
