### ISSUE TITLE
API Documentation is not available

### ISSUE THREAD

**Issue by cocxtrash** [pallets-eco/flask-caching#348]
**URL:** https://flask-caching.readthedocs.io/en/latest/api.html

![Screenshot 2022-05-09 at 04-53-14 API — Flask-Caching 1 0 0 documentation](https://user-images.githubusercontent.com/76768193/167343408-7167b10c-5989-40f9-8795-8a159a8a3c79.png)

**Browser:** Latest Firefox.

**Comment by northernSage** [comment]
@cocxtrash  Check https://cachelib.readthedocs.io/en/stable/ for details on backend classes (we now use cachelib as backend). I will update the docs soon, thanks for letting us know!
