### ISSUE TITLE
Redis Sentinel backend not working after Cachelib rewrite (1.11.0)

### ISSUE THREAD

**Issue by peter-slovak** [pallets-eco/flask-caching#362]
I'm having problems using `CACHE_TYPE="redissentinel"` since `Flask-Caching` switched to `cachelib`. Instead of querying any of the read/write clients, the `get_many()` method is trying to contact the default `localhost:6379` address. This behavior appeared strictly after upgrading from `1.10.1` to `1.11.1` and disappeared after downgrade.

Related settings in Flask configuration:
```python
    CACHE_TYPE = "redissentinel"
    CACHE_DEFAULT_TIMEOUT = 300
    CACHE_KEY_PREFIX = "cache_"
    CACHE_REDIS_SENTINELS = [("tasks.redis-sentinel", 26379)]
    CACHE_REDIS_SENTINEL_MASTER = "mymaster"
```

From the brief research I did, this is what looks suspicious to me: https://github.com/pallets-eco/flask-caching/pull/308/files#diff-d15a59e5c66734a6b6d638efe7582b3a147d5a4213dc3b3ca4e3672c50607ae1R62

You see, in `1.10.1`, the `get_many()` method queried `self._read_clients` that was initialized in `RedisCache.__init__()` and overloaded in `RedisSentinelCache.__init__()`. However in `1.11.1` the `get_many()` method is now inherited from the `CachelibRedisCache` superclass, which internally uses `self._client` initialized to default values (`localhost:6379`). Although we keep overloading `self._write_client` and `self._read_clients` in `RedisSentinelCache.__init__()`, this has no effect.

Environment:

- Python version: 3.10
- Flask-Caching version: 1.11.1

**Comment by peter-slovak** [comment]
FWIW, the situation is probably the same for `RedisClusterCache`, although I haven't tested.

**Comment by lexisstv** [comment]
Confirm - Sentinel stop working. 
May be problems here:
RedisSentinelCache.__init__() -> RedisCache.__init__() -> (ADDED in 1.11.1 from cachelib import RedisCache as CachelibRedisCache) CachelibRedisCache.__init__() -> ... Redis client initializes connection pool with default arguments (localhost)

**Comment by northernSage** [comment]
Already writing a fix fir this. It may take a few days due to lack of time, but it will be out soon. Meanwhile, please downgrade as suggested.

**Comment by peter-slovak** [comment]
Thank you for the effort to fix this @northernSage ! :hugs: :+1:
