### ISSUE TITLE
FileSystemCache broken in 1.11.1

### ISSUE THREAD

**Issue by gumptionthomas** [pallets-eco/flask-caching#363]
FileSystemCache appears to be broken in 1.11.1 (pickle errors) as a result of the `cachelib` integration.

To reproduce the bug, just use the `FileSystemCache` as a backend.

When attempting to read an existing key from the cache, you will get an error every time:

```
Traceback (most recent call last):
  File "test.py", line 30, in get
    if (c := cache.get(key)) is None:
  File "/usr/local/lib/python3.9/site-packages/flask_caching/__init__.py", line 190, in get
    return self.cache.get(*args, **kwargs)
  File \"/usr/local/lib/python3.9/site-packages/flask_caching/backends/filesystemcache.py\", line 120, in get
    pickle_time = pickle.load(f)
ValueError: unsupported pickle protocol: 198
``` 

I believe the bug is caused by the following:

`FileSystemCache.get()` is overloaded (inherited from `CachelibFileSystemCache`) but doesn't replicate the same pickle logic as the inherited and non-overloaded `CachelibFileSystemCache.set()` method. In particular, the `set()` method stores the `pickle_time` in the first 4 bytes and then the actual pickle data. The overloaded `get()` method simply tries to use `pickle.load()` on the whole thing and blows up due to the first 4 bytes not being "pickle" data.

Environment:

- Python version: 3.10.4
- Flask-Caching version: 1.11.1

**Comment by gumptionthomas** [comment]
I think `cachelib` 0.7.0 is incompatible with `flask-caching` 1.11.1 in terms of `FileSystemCache`.

It looks like [this](https://github.com/pallets-eco/cachelib/commit/6206d5877b550a4cd8532d0fb5557b3903734435) is the `cachelib` commit that broke the overloaded `FileSystemCache.get()` implementation. It was committed one day after the commit to `filesystemcache.py` that made the switch to using `cachelib`. Doh! :-)

Downgrading`cachelib` to 0.6.0 resolved this issue for me.

**Comment by sorenwacker** [comment]
I am getting this error messages even with 1.10.1:
> ERROR:flask_caching.backends.filesystemcache:get key 'progress' -> invalid load key, '\x15'.
However, the cache seems to work. 
When installing 1.11 it does not work.

**Comment by northernSage** [comment]
@gumptionthomas Thanks for the detailed write up! Actual issue that caused this problem, though, was the fact that flask-caching install requirements were not yet pinned, which I have just now realized (oops). Fixing it now.
