### ISSUE TITLE
Relax dependency version pins in setup.py?

### ISSUE THREAD

**Issue by snarfed** [pallets-eco/flask-caching#382]
Hi! First of all, thank you for maintaining flask-caching. It's great!

I noticed that you all pinned your dependencies' versions recently in #368. Flask recently released v2.1.3, but flask-caching users won't be able to upgrade until you update your pin. Any chance you'd consider relaxing it to just major version, or anything else that you know you explicitly depend on and couldn't upgrade past? Specific version pins are great for applications, but overly restrictive for libraries since they cause problems like this. [More on this here](https://depfu.com/blog/2017/03/22/a-brief-history-of-dependency-management) (search for _library dependencies_).

Thanks in advance!

**Comment by iROCKBUNNY** [comment]
+1

**Comment by snarfed** [comment]
Thank you!
