### ISSUE TITLE
Use cachelib version above 0.9.0 

### ISSUE THREAD

**Issue by colinet** [pallets-eco/flask-caching#535]
Currently, Flask-caching requires cachelib "cachelib >= 0.9.0, < 0.10.0"
There is a more recent version of cachelib (0.10.2). 

Is there any plan to upgrade this dependancy ?

**Comment by rimvislt** [comment]
any updates on this one?

**Comment by eduardoalvarenga** [comment]
`cachelib==0.11.0` is now released and this is still a problem
